Bsr_light/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib import admin
import polls.views
from polls.models import Wiec

from django.shortcuts import redirect

def Auth_check(f):
	def Auth_check2(request, *args, **kwargs):
	    if request.user.is_authenticated:
	        return f(request, *args, **kwargs)
	    else:
	        return redirect("polls:login")
	return Auth_check2

def Active():
	def Active2(request, *args, **kwargs):
	    if len(Wiec.objects.filter(Active=True)) == 0:
	        return polls.views.Base.Home(request, *args, **kwargs)
	    else:
	    	return redirect("polls:queue")
	return Active2

urlpatterns = [
    path('', Auth_check(Active()), name='home'),
    path('polls/', include('polls.urls'),),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

Bsr_light/polls/urls.py
from django.urls import path
from django.http import HttpResponseRedirect, HttpResponseForbidden
from . import views
from django.shortcuts import redirect
from .models import Question, Vote
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Wiec

def Active_wiec(f):
	def Active2(request, *args, **kwargs):
		if Wiec.objects.filter(Active=True).exists():
			return f(request, *args, **kwargs)
		else:
			return redirect("home")
	return Active2

def not_Finnished_wiec(f):
	def Active2(request, *args, **kwargs):
		if Wiec.objects.filter(Finnished=False).exists():
			return redirect("polls:activeWiec")
		else:
			return f(request, *args, **kwargs)

	return Active2

def active_voting(f):
	def active_voting2(request, *args, **kwargs):
		active_question = Question.objects.filter(active=True).exists()
		user = User.objects.get(username = request.user)
		Prezydium_bool = user.groups.filter(name="Prezydium").exists()
		if active_question == True and Prezydium_bool == False:
			q = Question.objects.filter(active=True)
			for question in q:
				for answer in question.choice_set.filter():
					if Vote.objects.filter(user=user, answer = answer).exists():
						return f(request, *args, **kwargs)
			return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
		else:
			return f(request, *args, **kwargs)
	return active_voting2


def prezydium_auth(f):
	def prezydium_auth2(request, *args, **kwargs):
		Prezydium_bool = User.objects.get(username = request.user).groups.filter(name="Prezydium").exists()
		if Prezydium_bool:
				return f(request, *args, **kwargs)
		else:
			return views.ErrorView.Forbidden(request)
	return prezydium_auth2

def organizator_auth(f):
	def organizator_auth2(request, *args, **kwargs):
		organizator_bool = User.objects.get(username = request.user).groups.filter(name="Organizator").exists()
		if organizator_bool:
				return f(request, *args, **kwargs)
		else:
			return HttpResponseForbidden()
	return organizator_auth2

def Auth_check(f):
	def Auth_check2(request, *args, **kwargs):
		if request.user.is_authenticated:
			return f(request, *args, **kwargs)
		else:
			return redirect("polls:login")
	return Auth_check2

app_name = 'polls'
urlpatterns = [

	path('', Auth_check(views.Base.Home), name='Home'),
	path('data', Auth_check(views.Base.json), name='BaseData'),
	path('noWiec', Auth_check(views.Base.noWiec), name='noWiec'),
	path('activeWiec', Auth_check(views.Base.activeWiec), name='activeWiec'),

	path("login", views.Authorization.login_view, name="login"),
	path('logout', views.Authorization.logout_view, name='logout'),

	path('wiec_generate', Auth_check(not_Finnished_wiec(organizator_auth(views.WiecArchive.create))), name='wiec_generate'),

	path('generate', Auth_check(Active_wiec(prezydium_auth(views.GeneratePolls.view))), name='generate'),
	path('generate_firstVote', Auth_check(Active_wiec(prezydium_auth(views.GeneratePolls.firstVote))), name='generate_firstVote'),


	path('queue',  Auth_check(Active_wiec(active_voting(views.QueueView.view))), name='queue'),

	path('queue/open', Auth_check(prezydium_auth(views.QueueView.Open)), name='StartQueue'),
	path('queue/close', Auth_check(prezydium_auth(views.QueueView.Close)), name='StopQueue'),


	path('queue/data', Auth_check(views.QueueView.Json), name='Qdata'),
	path('queue/add', Auth_check(views.QueueView.add), name='add'),
	path('queue/delete', Auth_check(views.QueueView.delete), name='delete'),
	path('queue/delete_first', Auth_check(views.QueueView.delete_first), name='delete_first'),

	path('wiecJson/', Auth_check(views.WiecArchive.json), name='wiecJson'),

	path('wiec/<int:wiec_id>/', Auth_check(views.WiecArchive.index), name='wiecIndex'),
	path('StartWiec/', Auth_check(views.WiecArchive.StartWiec), name='StartWiec'),
	path('StopWiec/', Auth_check(views.WiecArchive.StopWiec), name='StopWiec'),
	path('wiec_summary/<int:wiec_id>/', Auth_check(views.WiecArchive.summary), name='wiecSummary'),

	path('Verify/verify_index/<int:wiec_id>/', Auth_check(views.Verify.manager_index), name='verifyManager_index'),
	path('Verify/index/<int:wiec_id>/', Auth_check(views.Verify.index), name='verifyIndex'),
	path('Verify/manager/<int:id>/<int:to_verify>/', Auth_check(views.Verify.manager), name='verifyManager'),

	path('<int:question_id>/', Auth_check(views.Polls.detail), name='detail'),

	path('<int:pk>/results/', Auth_check(active_voting(views.Polls.results)), name='results'),
	path('voted/', Auth_check(views.Polls.voted), name='voted'),
	
	path('<int:pk>/again/', Auth_check(views.Polls.again), name='again'),
	path('<int:pk>/again/data/', Auth_check(views.Polls.Json), name='data'),

	path('<int:question_id>/vote/', Auth_check(views.Polls.vote), name='vote'),
	path('close/', Auth_check(views.Polls.Close), name='StopVote'),

	path('<int:question_id>/results_gen/', Auth_check(views.GeneratePolls.results), name='results_gen'),

]

Bsr_light/polls/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class Wiec(models.Model):
    Title = models.CharField(max_length=200)
    StartDate = models.DateTimeField()
    Active = models.BooleanField(default=False)
    Queue_active = models.BooleanField(default=False)
    Finnished = models.BooleanField(default=False)
    Summary = models.BooleanField(default=False)
    
    def __str__(self):
        return self.Title

class Topic(models.Model):
    topic_text = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    # description = models.CharField(null=True, max_length=500)
    # contribution = models.CharField(null=True, max_length=500)
    # help = models.CharField(null=True, max_length=50)
    # introduction = models.BooleanField(default=False)
    # money = models.BooleanField(default=False)

    wiec = models.ForeignKey(Wiec, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.topic_text

class Announcement(models.Model):
    announcement_text = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    # description = models.CharField(null=True, max_length=500)

    wiec = models.ForeignKey(Wiec, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.announcement_text

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    multiple_votes = models.BooleanField(default=False)
    ranked_system = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    wiec = models.ForeignKey(Wiec, on_delete=models.CASCADE)

    class Meta:
        get_latest_by='pub_date'
            
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
    
class Choice(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    
    votes = models.IntegerField(default=0)
    owner = models.ManyToManyField(User, through='Vote')

    def __str__(self):
        return self.choice_text

class Vote(models.Model):
    #id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Choice, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)

    def __str__(self):
        return  'user id: {} and answer id: {}'.format(self.user.id, self.answer.id)

    class Meta:
        unique_together = [['user', 'answer']]
    

class Queue(models.Model):
    number = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    now = models.IntegerField(default=None, blank=True, null=True)
    
    def __str__(self):
        return self.user.username





Bsr_light/polls/forms.py
from django.forms import ModelForm
from django import forms
from .models import Question, Choice, Topic, Wiec, Announcement

class UserForm(forms.Form):
	username = forms.CharField(label="login", max_length=100, required=True)
	password = forms.CharField(label="password", max_length=100, required=True)

class GhostUserForm(forms.Form):
	username = forms.CharField(label="login", max_length=20, required=True)

class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = ['question_text', 'ranked_system']

class ChoiceForm(ModelForm):

	class Meta(object):
		model = Choice
		fields = ['choice_text']

class TopicForm(ModelForm):

	class Meta(object):
		model = Topic
		fields = ['topic_text']

class AnnouncementForm(ModelForm):

	class Meta(object):
		model = Announcement
		fields = ['announcement_text']

class WiecForm(ModelForm):

	class Meta(object):
		model = Wiec
		fields = ['Title', 'StartDate']

Bsr_light/polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}
{% load static %}

{% block content %}
  	<link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}">

	<h1>{{ question.question_text }}</h1>

	{% if error_message %}<p><strong>Nie zaznaczyłeś żadnej opcji.</strong></p>{% endif %}

	<form id="form-container" action="{% url 'polls:vote' question.id %}" onsubmit="return validateForm()" method="post">
		{% csrf_token %}
		<ul class="choice" id="choice">
			{% for choice in question.choice_set.all %}
				<li class="choice">
					<div class="wrapper">
						<div class="awrap">
		    				<button type="button" class="sub" id="{{ choice.choice_text }}" onclick="check('{{ choice.choice_text }}')"><p style='overflow-wrap: anywhere;'>{{ choice.choice_text }}</p></button
		    			</div>
			    	</div>
				</li>
			{% endfor %}
		</ul>

		<div class="save_wrapper">
	        <button type="submit" class="save_btn">Zagłosuj</button>
	    </div>
	</form>

	<script>
		let checked = ""
		function check(name){
			checked = name;
			btns = document.getElementsByClassName("sub")

			for (btn of btns){
				btn.parentElement.parentElement.style.background = 'linear-gradient(to right, #ec79ff, #a3e2ff, #ec79ff)';
				btn.parentElement.style.background = "#222"
				btn.style.background = "#222"
			}
			clicked = document.getElementById(name)

			clicked.parentElement.parentElement.style.background = 'linear-gradient(to right, #f5bf42, #8742f5)';
			clicked.parentElement.style.background = "#111"
			clicked.style.background = "#111"
		}
		
		function validateForm(){
			let form = document.getElementById("form-container")


			let string = `<input type="hidden"  name="choice" id="choice" required="" value='${checked}'>`
			form.insertAdjacentHTML('beforeend', string)
		}

	</script>
{% endblock %}

Bsr_light/polls/templates/polls/detail_count.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}
{% load static %}

{% block content %}
  	<link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}">

	<h1>{{ question.question_text }}</h1>

	
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form id="form-container" action="{% url 'polls:vote' question.id %}" onsubmit="return validateForm()" method="post">
		{% csrf_token %}
		<div class="tooltip">
			<span class="tooltip-span"><p class="tooltip-icon">?</p></span>
			<div class="tooltip-content" id="tooltip-content">
				<p>Wybierz swoje opcje w odpowiedniej kolejności. Nr 1 jest najważniejsze</p>
			</div>
			<div class="triangle"></div>
		</div>
		<ul class="choice_rank" id="choice">
			{% for choice in question.choice_set.all %}
				<li class="choice_rank">
					<div class="wrapper">
						<div class="awrap">
							<span class="List" name="{{choice.id}}" id="choice{{ forloop.counter }}">{{ choice.choice_text }}
						</div>
					</div>
				</li>
			{% endfor %}
		</ul>
		<div class="save_wrapper">
	        <button type="submit" class="save_btn">Zagłosuj</button>
	    </div>
	</form>

	<script src="https://raw.githack.com/SortableJS/Sortable/master/Sortable.js"></script>
	<script>
		new Sortable(choice, {
		   animation: 150,
		   swapThreshold: 0.5,
		});


		function validateForm(){
			let form = document.getElementById("form-container")

			let list = document.querySelectorAll(".List")
			let RankedList = []

			for (let ele of list){
				RankedList.push(ele.getAttribute('name'))
			}
			console.log(RankedList)
			let string = `<input type="hidden" name="RankedList" id="id_RankedList" required="" value='` + RankedList + `''>`
			form.insertAdjacentHTML('beforeend', string)
		}
			
	</script>
{% endblock %}

Bsr_light/polls/templates/polls/generate.html
{% extends 'base.html' %}

{% block content %}
	{% load static %}
  	<link rel="stylesheet" type="text/css" href="{% static 'polls/generate.css' %}">

	<img class="logo" src="{% static 'polls/images/wiecOS_logo.png' %}">

    <h2>Generator Głosowań</h2>
    
    <form id="form-container" method="post">

        {% csrf_token %}
        {{ formset.management_form }}
        <div class="temp" style="position: relative;">
            <div class="wrapper">
                <div class="awrap">
                    <label for="id_question_text"></label>
                    <input type="text" name="question_text" maxlength="200" required="" id="id_question_text" placeholder="Pytanie :">
                </div>
            </div>
            <div class="Side">
                <label for="id_ranked_system">&nbsp;</label>
                <div class="wrapper_checkbox">
                    <label class="checkbox_label">
                        <input type="checkbox" class="checkbox" name="ranked_system" value="0" id="id_ranked_system">
                        <span clas="span_checkbox"></span>
                    </label>
                </div>

                <div class="tooltip">
                    <span class="tooltip-span"><p class="tooltip-icon">?</p></span>
                    <div class="tooltip-content" id="tooltip-content">
                        <p>Czy chcesz użyć systemu rankingowego? Głosujesz poprzez ustalenie kolejności opcji.</p>
                    </div>
                    <div class="triangle"></div>
                </div>
            </div>
        </div>

        <!-- Kopiowanie contenerów -->
        {% for form in formset %}
            
        	<div class="wrapper">
    			<div class="awrap">
    				<div class="choice_form">
                		{{ form }}
                      
                        <p></p>
                	</div>
                </div>
            </div>
        {% endfor %}

        <div class="login_wrapper">
            <input class='login_Btn' type="submit" value="Dodaj opcję" name="Submit" id="add-form" />
        </div>
        
        <div class="save_wrapper">
            <button type="submit" class="save_btn">Zapisz</button>
        </div>
    </form>


    <script>
        let choice = document.getElementById("id_choice_set-0-choice_text")

        choice.labels[0].textContent = ""
        choice.placeholder = "Opcja : "
        let wrapper = document.querySelectorAll(".wrapper")
        let awrap = document.querySelectorAll(".awrap")
        let login_wrapper = document.querySelector(".login_wrapper")

        let choiceForm = document.querySelectorAll(".choice_form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")

        let total_forms = document.getElementById('id_choice_set-TOTAL_FORMS')

        let formNum = choiceForm.length-1
        addButton.addEventListener('click', addForm)
        console.log(choiceForm)


        function cancelField(){
            choiceForm = document.querySelectorAll(".choice_form")
            formNum = choiceForm.length-1

            let field = document.getElementById(`choice_set-${formNum}-choice_text`)
            let wrapper_temp = field.parentElement.parentElement.parentElement
            
            wrapper_temp.remove()

            choiceForm = document.querySelectorAll(".choice_form")
            formNum = choiceForm.length-1
            if(formNum != 0){
                field = document.getElementById(`choice_set-${formNum}-choice_text`)

                let cancelBtn = document.createElement("SPAN")
                cancelBtn.setAttribute('class', 'cancelBtn') 
                cancelBtn.setAttribute('id', 'cancelBtn') 
                cancelBtn.setAttribute('onclick', 'cancelField()')
                cancelBtn.innerHTML = '&times;'
                field.after(cancelBtn)
            }
        }

        function addForm(e){

            e.preventDefault()

            let newwrapper = wrapper[1].cloneNode(false)
            let newawrap = awrap[1].cloneNode(false)

            let newForm = choiceForm[0].cloneNode(true)

            formNum++

            console.log(newForm.children[1])

            newForm.children[0].setAttribute('for', `choice_set-${formNum}-choice_text`) /*Label*/
            newForm.children[1].setAttribute('id', `choice_set-${formNum}-choice_text`) /*Input*/
            newForm.children[1].setAttribute('name', `choice_set-${formNum}-choice_text`) /*Input*/
            newForm.children[1].value = ""; /*Input*/

            newawrap.appendChild(newForm);

            if (document.getElementById("cancelBtn")){
                let cancelBtn = document.getElementById("cancelBtn")
                cancelBtn.remove()
            }

            let cancelBtn = document.createElement("SPAN")
            cancelBtn.setAttribute('class', 'cancelBtn') 
            cancelBtn.setAttribute('id', 'cancelBtn') 
            cancelBtn.setAttribute('onclick', 'cancelField()')
            cancelBtn.innerHTML = '&times;'

            newawrap.appendChild(cancelBtn);


            newwrapper.appendChild(newawrap);

            

            container.insertBefore(newwrapper, login_wrapper)
            
            

            console.log(choiceForm)
            let value = parseInt(total_forms.getAttribute('value'))
            total_forms.setAttribute('value', value + 1)

        }
    </script>
    {% block script %}
	{% endblock %}
{% endblock %}

Bsr_light/polls/templates/polls/results.html
{% extends 'base.html' %}

{% block title %}Results{% endblock %}
{% load static %}

{% block content %}
  	<link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}">

  	{% block Again %}
	{% endblock %}

	<h1 style="width: 90vw; overflow-wrap: break-word;">{{ question.question_text }}</h1>

	<h2>Wyniki głosowania:</h2>

	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

  	<div class="chartWrapper">
      <div class="awrap"> 
				<canvas id="myChart" data-url='{% url "polls:data" question.id %}'></canvas> 
			</div>
		</div>
		
		
	<script>
		$(function (){
			var $myChart = $("#myChart");
			$.ajax({
				url: $myChart.data("url"),

				success: function(data){

					Labels = data.Labels
					Data = data.Data

					final_data = Labels.map(function(d, i){
						return {
							label: d,
							data: Data[i] || 0
						};
					});
					sorted_final_data = final_data.sort(function(a,b) {
						return b.data > a.data;
					});

					newLabels = []
					newData = []

					sorted_final_data.forEach(function(d){
						newLabels.push(d.label);
						newData.push(d.data);
					});

					var ctx = $myChart[0].getContext("2d");

					
					var gradient = ctx.createLinearGradient(0, 0, 0, 600);
					gradient.addColorStop(0, '#f5bf42');
					gradient.addColorStop(0.5, '#8742f5');
					gradient.addColorStop(1, 'red');

					new Chart(ctx, {
						type: 'bar',
						data: {
							labels: newLabels,
							datasets:[{
								fillColor: gradient,
								label: "Wyniki",
								backgroundColor: gradient,
								data: newData,
							}]
						},
						options: {
							legend: {
								labels: {
									fontColor: "white"
								}
							},
							scales: {
								yAxes: [{
									display: true,
									ticks: {
										beginAtZero: true,
										stepSize: 1,
										fontColor: "white"
									}
								}],
								xAxes: [{
									ticks: {
										fontColor: "white",
									}
								}]
							}
						}
					});

				}
			});
		});
	</script>

{% endblock %}

Bsr_light/polls/templates/polls/verify_manager.html
{% extends 'base.html' %}
{% load static %}

{% block title %}TopicManager{% endblock %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/verify.css' %}">
  <div class="column">
    <h1>Ogłoszenia</h1>
    {% if wiec_announcement_list %}
      <ul class="quest">
        {% for announcement in wiec_announcement_list %}
          <li class="quest">
            <div class="wrapper">
              <div class="awrap"> 
                <p class="text">{{ announcement.announcement_text }}</p>
                {% if announcement.user.first_name%}
                  <h2>{{ announcement.user.first_name }}  {{ announcement.user.last_name }} </h2>
                {% else %}
                  <h2>{{ announcement.user.username }}</h2>
                {% endif %}      
                <form action="{% url 'polls:verifyManager' announcement.id 0 %}" method="post">
                  {% csrf_token %}
                  <div class="save_wrapper">
                    <input class="btn" name="verify" type="submit" value="Zatwierdź"/>

                    <input class="btn" name="delete" type="submit" value="Usuń"/>
                  </div>
                </form>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Nie ma żadnych ogłoszeń do sprawdzenia</p>
    {% endif %}
  </div>
  <div class="column">
    <h1>Tematy</h1>
    {% if wiec_topic_list %}
      <ul class="quest">
        {% for topic in wiec_topic_list %}
          <li class="quest">
            <div class="wrapper">
              <div class="awrap"> 
                <p class="text">{{ topic.topic_text }}</p>
                {% if topic.user.first_name%}
                  <h2>{{ topic.user.first_name }}  {{ topic.user.last_name }} </h2>
                {% else %}
                  <h2>{{ topic.user.username }}</h2>
                {% endif %}      
                <form action="{% url 'polls:verifyManager' topic.id 1%}" method="post">
                  {% csrf_token %}
                  <div class="save_wrapper">
                    <input class="btn" name="verify" type="submit" value="Zatwierdź"/>

                    <input class="btn" name="delete" type="submit" value="Usuń"/>
                  </div>
                </form>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Nie ma żadnych tematów do sprawdzenia</p>
    {% endif %}
  </div>
{% endblock %}

Bsr_light/polls/templates/polls/voted.html
{% extends 'base.html' %}

{% block content %}
	{% load static %}

	<img class="logo" style="width:600px; top:0; position:relative; margin-top: -10vh;" src="{% static 'polls/images/wiecOS_logo.png' %}">

    <h1 style="margin-bottom: -25px">Dziękujemy za zagłosowanie</h1>
    <h1>Podliczamy teraz głosy</h1>
    <img height="300" width="300" class="check" src="{% static 'polls/images/check.svg' %}">
    <form action="{% url 'polls:queue'%}">
        <div class="btn_wrapper" style='margin-top:20px;'>
            <div class="btn_awrap" style='width:auto;'><input type="submit" class="btn" value="Powrót na stronę główną" />
            </div>
        </div>
    </form>
{%endblock%}

{% block url_redirect %}
    location.href = `{%url "polls:results" last_quest %}`
{%endblock%}

Bsr_light/polls/templates/polls/wiec_generate.html
{% extends 'base.html' %}

{% block content %}
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/wiec_generate.css' %}">

    <img class="logo" src="{% static 'polls/images/wiecOS_logo.png' %}">
    
  	<form id="form-container" onsubmit="return validateForm()" method="post">
        {% csrf_token %}
        

        {{ Wform.Title.errors }}

        <div class=wrapper>
            <div class="awrap"> 
                <input id="id_Title" required class="Title" type="text" name="Title" autocapitalize="none" maxlength="150" placeholder="Tytuł"> 
            </div>
        </div>

        <div class=wrapper>
            <div class="awrap"> 
                <input id="id_Date" required class="Date" type="date" name="Date" autocapitalize="none" maxlength="150" placeholder="Data"> 
            </div>
        </div>

        <div class=wrapper>
            <div class="awrap"> 
                <input id="id_Time" required class="Time" type="time" name="Time" autocapitalize="none" maxlength="150" placeholder="Godzina"> 
            </div>
        </div>
        
        <div class="save_wrapper">
            <button type="submit" id="save_btn" class="save_btn">Stwórz wiec</button>
        </div>
        
    </form>
    <script>
        let submit = document.getElementById("save_btn")

        let form = document.getElementById("form-container")


        function validateForm(){
            

            let date = document.getElementById("id_Date").value
            let time = document.getElementById("id_Time").value

            let dateTime = date + " " + time

            let string = `<input type="hidden" name="StartDate" id="id_StartDate" required="" value="` + dateTime + `">`

            form.insertAdjacentHTML('beforeend', string)

            
        }

    </script>
{% endblock %}

Bsr_light/polls/templates/polls/wiec_index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Index{% endblock %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/index.css' %}">
  <h1 style="margin: 0; font-size: 80px">{{Title}}</h1>
  <h2 style="margin: 0; font-size: 30px;">{{Date}}</h2>  
  {% if Summary == True %}
    <div class="btn_wrapper"><a class="btn_awrap" href="{% url 'polls:wiecSummary' id %}">Podsumowanie Wiecu</a></div>
  {% endif %}

  <h1 style="font-size: 60px;">Tematy</h1>
  {% if verified %}
    <ul class="quest">
      {% for topic in verified %}
        <li class="quest"><div class="wrapper"><div class="awrap">{{ topic.topic_text }}</div></div></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Brak dostępnych tematów</p>
  {% endif %}

  <h1 style="margin-top: 40px; margin-bottom: 0; font-size: 60px;">Głosowania</h1>
  {% if wiec_question_list %}
    <ul class="quest">
      {% for question in wiec_question_list %}
        <p>Data publikacji: {{question.pub_date}}</p> 
        <li class="quest"><div class="btn_wrapper"><a class="btn_awrap" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></div></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Brak dostępnych głosowań</p>
  {% endif %}
{% endblock %}