Bsr_light/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib import admin
import polls.views
from polls.models import Wiec

from django.shortcuts import redirect

def Auth_check(f):
	def Auth_check2(request, *args, **kwargs):
	    if request.user.is_authenticated:
	        return f(request, *args, **kwargs)
	    else:
	        return redirect("polls:login")
	return Auth_check2

def Active():
	def Active2(request, *args, **kwargs):
	    if len(Wiec.objects.filter(Active=True)) == 0:
	        return polls.views.Base.Home(request, *args, **kwargs)
	    else:
	    	return redirect("polls:queue")
	return Active2

urlpatterns = [
    path('', Auth_check(Active()), name='home'),
    path('polls/', include('polls.urls'),),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

Bsr_light/polls/urls.py
from django.urls import path
from django.http import HttpResponseRedirect, HttpResponseForbidden
from . import views
from django.shortcuts import redirect
from .models import Question, Vote
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Wiec

def Active_wiec(f):
	def Active2(request, *args, **kwargs):
		if Wiec.objects.filter(Active=True).exists():
			return f(request, *args, **kwargs)
		else:
			return redirect("home")
	return Active2

def not_Finnished_wiec(f):
	def Active2(request, *args, **kwargs):
		if Wiec.objects.filter(Finnished=False).exists():
			return redirect("polls:activeWiec")
		else:
			return f(request, *args, **kwargs)

	return Active2

def active_voting(f):
	def active_voting2(request, *args, **kwargs):
		active_question = Question.objects.filter(active=True).exists()
		user = User.objects.get(username = request.user)
		Prezydium_bool = user.groups.filter(name="Prezydium").exists()
		if active_question == True and Prezydium_bool == False:
			q = Question.objects.filter(active=True)
			for question in q:
				for answer in question.choice_set.filter():
					if Vote.objects.filter(user=user, answer = answer).exists():
						return f(request, *args, **kwargs)
			return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
		else:
			return f(request, *args, **kwargs)
	return active_voting2


def prezydium_auth(f):
	def prezydium_auth2(request, *args, **kwargs):
		Prezydium_bool = User.objects.get(username = request.user).groups.filter(name="Prezydium").exists()
		if Prezydium_bool:
				return f(request, *args, **kwargs)
		else:
			return views.ErrorView.Forbidden(request)
	return prezydium_auth2

def organizator_auth(f):
	def organizator_auth2(request, *args, **kwargs):
		organizator_bool = User.objects.get(username = request.user).groups.filter(name="Organizator").exists()
		if organizator_bool:
				return f(request, *args, **kwargs)
		else:
			return HttpResponseForbidden()
	return organizator_auth2

def Auth_check(f):
	def Auth_check2(request, *args, **kwargs):
		if request.user.is_authenticated:
			return f(request, *args, **kwargs)
		else:
			return redirect("polls:login")
	return Auth_check2

app_name = 'polls'
urlpatterns = [

	path('', Auth_check(views.Base.Home), name='Home'),
	path('data', Auth_check(views.Base.json), name='BaseData'),
	path('noWiec', Auth_check(views.Base.noWiec), name='noWiec'),
	path('activeWiec', Auth_check(views.Base.activeWiec), name='activeWiec'),

	path("login", views.Authorization.login_view, name="login"),
	path('logout', views.Authorization.logout_view, name='logout'),

	path('wiec_generate', Auth_check(not_Finnished_wiec(organizator_auth(views.WiecArchive.create))), name='wiec_generate'),

	path('generate', Auth_check(Active_wiec(prezydium_auth(views.GeneratePolls.view))), name='generate'),
	path('generate_firstVote', Auth_check(Active_wiec(prezydium_auth(views.GeneratePolls.firstVote))), name='generate_firstVote'),


	path('queue',  Auth_check(Active_wiec(active_voting(views.QueueView.view))), name='queue'),

	path('queue/open', Auth_check(prezydium_auth(views.QueueView.Open)), name='StartQueue'),
	path('queue/close', Auth_check(prezydium_auth(views.QueueView.Close)), name='StopQueue'),


	path('queue/data', Auth_check(views.QueueView.Json), name='Qdata'),
	path('queue/add', Auth_check(views.QueueView.add), name='add'),
	path('queue/delete', Auth_check(views.QueueView.delete), name='delete'),
	path('queue/delete_first', Auth_check(views.QueueView.delete_first), name='delete_first'),

	path('wiecJson/', Auth_check(views.WiecArchive.json), name='wiecJson'),

	path('wiec/<int:wiec_id>/', Auth_check(views.WiecArchive.index), name='wiecIndex'),
	path('StartWiec/', Auth_check(views.WiecArchive.StartWiec), name='StartWiec'),
	path('StopWiec/', Auth_check(views.WiecArchive.StopWiec), name='StopWiec'),
	path('wiec_summary/<int:wiec_id>/', Auth_check(views.WiecArchive.summary), name='wiecSummary'),

	path('Verify/verify_index/<int:wiec_id>/', Auth_check(views.Verify.manager_index), name='verifyManager_index'),
	path('Verify/index/<int:wiec_id>/', Auth_check(views.Verify.index), name='verifyIndex'),
	path('Verify/manager/<int:id>/<int:to_verify>/', Auth_check(views.Verify.manager), name='verifyManager'),

	path('<int:question_id>/', Auth_check(views.Polls.detail), name='detail'),

	path('<int:pk>/results/', Auth_check(active_voting(views.Polls.results)), name='results'),
	path('voted/', Auth_check(views.Polls.voted), name='voted'),
	
	path('<int:pk>/again/', Auth_check(views.Polls.again), name='again'),
	path('<int:pk>/again/data/', Auth_check(views.Polls.Json), name='data'),

	path('<int:question_id>/vote/', Auth_check(views.Polls.vote), name='vote'),
	path('close/', Auth_check(views.Polls.Close), name='StopVote'),

	path('<int:question_id>/results_gen/', Auth_check(views.GeneratePolls.results), name='results_gen'),

]

Bsr_light/polls/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class Wiec(models.Model):
    Title = models.CharField(max_length=200)
    StartDate = models.DateTimeField()
    Active = models.BooleanField(default=False)
    Queue_active = models.BooleanField(default=False)
    Finnished = models.BooleanField(default=False)
    Summary = models.BooleanField(default=False)
    
    def __str__(self):
        return self.Title

class Topic(models.Model):
    topic_text = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    # description = models.CharField(null=True, max_length=500)
    # contribution = models.CharField(null=True, max_length=500)
    # help = models.CharField(null=True, max_length=50)
    # introduction = models.BooleanField(default=False)
    # money = models.BooleanField(default=False)

    wiec = models.ForeignKey(Wiec, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.topic_text

class Announcement(models.Model):
    announcement_text = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    # description = models.CharField(null=True, max_length=500)

    wiec = models.ForeignKey(Wiec, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.announcement_text

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    multiple_votes = models.BooleanField(default=False)
    ranked_system = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    wiec = models.ForeignKey(Wiec, on_delete=models.CASCADE)

    class Meta:
        get_latest_by='pub_date'
            
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
    
class Choice(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    
    votes = models.IntegerField(default=0)
    owner = models.ManyToManyField(User, through='Vote')

    def __str__(self):
        return self.choice_text

class Vote(models.Model):
    #id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Choice, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)

    def __str__(self):
        return  'user id: {} and answer id: {}'.format(self.user.id, self.answer.id)

    class Meta:
        unique_together = [['user', 'answer']]
    

class Queue(models.Model):
    number = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    now = models.IntegerField(default=None, blank=True, null=True)
    
    def __str__(self):
        return self.user.username





Bsr_light/polls/forms.py
from django.forms import ModelForm
from django import forms
from .models import Question, Choice, Topic, Wiec, Announcement

class UserForm(forms.Form):
	username = forms.CharField(label="login", max_length=100, required=True)
	password = forms.CharField(label="password", max_length=100, required=True)

class GhostUserForm(forms.Form):
	username = forms.CharField(label="login", max_length=20, required=True)

class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = ['question_text', 'ranked_system']

class ChoiceForm(ModelForm):

	class Meta(object):
		model = Choice
		fields = ['choice_text']

class TopicForm(ModelForm):

	class Meta(object):
		model = Topic
		fields = ['topic_text']

class AnnouncementForm(ModelForm):

	class Meta(object):
		model = Announcement
		fields = ['announcement_text']

class WiecForm(ModelForm):

	class Meta(object):
		model = Wiec
		fields = ['Title', 'StartDate']

Bsr_light/polls/templates/auth_base.html
<!-- templates/auth_base.html -->
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/base.css' %}">
<link rel="icon" href="{% static 'polls/images/icon.ico' %}"/>

<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}Auth_base{% endblock %}</title>
</head>
<body>
  <main>
  	<div class="main">
		{% block content %}
    	{% endblock %}
	</div>
  </main>
</body>
</html>

Bsr_light/polls/templates/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/base.css' %}">
<link rel="icon" href="{% static 'polls/images/icon.ico' %}"/>

<html ontouchmove>
<head>
  <meta charset="utf-8">
  <title>{% block title %}WiecOS{% endblock %}</title>
</head>

<body onclick tabIndex=0>
  <main>
		<span onclick="openNav()" class="open">
      <div style="margin-bottom: 10px;width: 80px;height: 10px;background-color: white;"></div>
      <div style="margin-bottom: 10px;width: 80px;height: 10px;background-color: white;"></div>
      <div style="margin-bottom: 10px;width: 80px;height: 10px;background-color: white;"></div>
	  </span>

		<div class="bubble">
			<span onclick="Bubble()" class="bubble-span" id="bubble-span"></span>
			<div class="bubble-content" id="bubble-content">
				<a href="{% url 'logout' %}">Wyloguj się</a>
			</div>
		</div>

    

		<div id="mySidenav" class="sidenav">
      <div id="Copyright" class="Copyright">&copy; Jakub Michałowski</div>
		  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
 

      

		</div>
		<div id="main" class="main">
		    {% block content %}
		    {% endblock %}
		</div>
    

  </main>


<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script>


	let bubble_span = document.getElementById("bubble-span")

	let username = "{{ user.username }}"

	bubble_span.innerHTML = '<p class="icon">' + username.charAt(0).toUpperCase() + '</p>'

	console.log(bubble_span)

	let nav = document.getElementById("mySidenav")

	nav.display = "none";

	function openNav() {
    let mql = window.matchMedia('(max-device-width: 600px)');
    if (mql.matches == true){
	    nav.style.width = "350px";
    } else {
      nav.style.width = "250px";
    }
	}

	function closeNav() {
	  nav.style.width = "0";
	}

  function Bubble() {
    let bubble_content = document.getElementById("bubble-content")
    if (bubble_content.style.width == "0px" || bubble_content.style.width == "" ){
      let mql = window.matchMedia('(max-device-width: 600px)');
      if (mql.matches == true){
        bubble_content.style.width = "auto";
      } else {
        bubble_content.style.width = "220px";
      }
    } else {
      bubble_content.style.width = "0";
    }
    
  }

  

	$(function (){
		String.prototype.replaceAt = function(index, replacement) {
      return this.substr(0, index) + replacement + this.substr(index + replacement.length);
    }

		$.ajax({
			url: '{% url "polls:wiecJson"%}',

			success: function(data){
          let string = ""
          if (data.latest_wiec == null || data.latest_wiec['Active'] == false){
            string += `<a style="padding-top: 60px;" href="{% url 'polls:Home' %}">Główna strona</a>`
          } else {
            string = `<a style="padding-top: 60px;" href="{% url 'polls:queue' %}">Główna strona</a>`
          }
          if (data.latest_wiec != null){
            string += `<a href="/polls/Verify/index/${data.latest_wiec['id']}/">Tematy i Ogłoszenia</a>`
          }
          {% for group in request.user.groups.all %}
            {% if group.name == 'Prezydium' %}
            if (data.latest_wiec != null){
              string += `<a href="/polls/Verify/verify_index/${data.latest_wiec['id']}/">Weryfikacja prezydium</a>`
            }

            string += `<a href="{% url 'polls:generate' %}">Generator głosowań</a>`
            {% endif %}
            {% if group.name == 'Organizator' %}
            string += `<a href="{% url 'polls:wiec_generate' %}">Generator wiecu</a>`
            {% endif %}
          {% endfor %}

          nav.insertAdjacentHTML('beforeend',string)
          
          if (data.Wiece != null){
            let arch = 0
            for (wiec of data.Wiece){
              let temp = ""
              let string = ''

              if (wiec['Finnished'] == true && arch == 0){
                string += '<p class=Bold>Archiwalne wiece:</p>'
                arch += 1
              }
              if (wiec['Active'] == true && wiec['id'] == data.latest_wiec['id']) {
                string += `<a href="/polls/wiec/${wiec['id'].toString()}/">Aktualny wiec</a>`
              } else {
                string += `<a href="/polls/wiec/${wiec['id'].toString()}/">${wiec['Title']}</a>`
              }

              let i = 0;

              for (question of data.Questions){
                if (question.wiec_id == wiec['id']){
                  temp += `<p>${question.question_text}</p>`
                  i += 1;
                }
                if (i==3){
                  break
                }
              }
              string += temp
              nav.insertAdjacentHTML('beforeend',string)
              }
            
          }

			}
	  	})
		})

  let old_data_base = {}
  setInterval(function (){
    $.ajax({
      url: '{% url "polls:BaseData"%}',
        success: function(data){
          if (old_data_base["active_question"] == true && data.active_question == false){
            alert("Głosowanie się zakończyło")
            {% block url_redirect %}
		        {% endblock %}
          }
          if (old_data_base["active_question"] == false && data.active_question == true){
            alert("Głosowanie się rozpoczęło")
            location.reload();
          }
          
          old_data_base["active_question"] = data.active_question
          
        },
        failure: function(data){
          console.log("failure");
        }
    })

  }, 3000);  
</script>
</body>
</html>

Bsr_light/polls/templates/first.html
{% extends 'base.html' %}

{% block title %}WiecOS{% endblock %}

{% block content %}

	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/first.css' %}">

	<img class="logo" src="{% static 'polls/images/wiecoslogo.svg' %}">
	{% if Planned %}
		<h1 class="first">{{ Title }}</h1>
		<h2 class="first">Następny wiec rozpocznie się o godzinie:</h2>
		<h2 class="first">{{ Hour }}:{{ Minute }}</h2>

		{% for group in request.user.groups.all %}
			{% if group.name == 'Prezydium' %}
				<form action="{% url 'polls:StartWiec'%}">
					<div class="StartWrapper">
					<input type="submit" class="StartBtn" value="Rozpocznij wiec" />
				</div>
				</form>
			{% endif %}
    	{% endfor %}
	{% else %}
		<h2 style="max-width: 700px;">Żaden wiec aktualnie nie jest zaplanowany</h2>
	{% endif %}
    
	<form id="form-container" method="post">
		{% csrf_token %}
		{{ formset.management_form }}
		<div class="tooltip">
			<span class="tooltip-span"><p class="tooltip-icon">?</p></span>
			<div class="tooltip-content" id="tooltip-content">
				<p style="margin: 5px;">Tutaj możesz zgłosić temat, który powinien być omówiony na wiecu</p>
			</div>
			<div class="triangle"></div>
		</div>
		<div class="wrapper">
			<div class="awrap">
				<label for="id_topic_text"></label>
				<input type="text" name="topic_text" maxlength="200" id="id_topic_text" placeholder="Temat">
			</div>
		</div>

		<div class="tooltip">
			<span class="tooltip-span"><p class="tooltip-icon">?</p></span>
			<div class="tooltip-content" id="tooltip-content">
				<p style="margin: 5px;">Tutaj możesz się zgłosić, aby przekazać ważne informacje społeczności szkolnej.</p>
			</div>
			<div class="triangle"></div>
		</div>

		<div class="wrapper">
			<div class="awrap">
			 	<label for="id_announcement_text"></label>
				<input type="text" name="announcement_text" maxlength="200" id="id_announcement_text" placeholder="Ogłoszenie">
			</div>
		</div>
		<div class="save_wrapper">
			<button type="submit" class="save_btn">Zgłoś</button>
		</div>
	</form>
	
	<script
		src="https://code.jquery.com/jquery-3.6.0.js"
		integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
		crossorigin="anonymous">
	</script>
	
	<script>
		let topic = document.getElementById("id_topic_text")

		topic.placeholder = "Temat" 
		topic.labels[0].textContent = ""

		let announcement = document.getElementById("id_announcement_text")

		announcement.placeholder = "Ogłoszenie"
		announcement.labels[0].textContent = ""
		
		setTimeout(function (){
			{% if topic_saved == True and announcement_saved == True %}
				alert("Twój temat i ogłoszenie zostały zgłoszone do prezydium")
			{% elif topic_saved == True %}
				alert("Twój temat został zgłoszony do prezydium")
			{% elif announcement_saved  == True %}
				alert("Twoje ogłoszenie zostało zgłoszone do prezydium")
			{% endif %}
		}, 100);
		
	</script>
{% endblock %}